source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'byebug', require: true
gem 'guard'
gem 'guard-rspec'
gem 'guard-rubocop'
gem 'rspec'
gem 'rubocop'
